version: '3'

services:
  memorybook_dev_database:
    image: postgres:14
    environment:
      POSTGRES_USER: mbdev
      POSTGRES_PASSWORD: mbdev
      POSTGRES_DB: memorybook-dev
    ports:
      - 5432:5432

  memorybook_test_database:
    image: postgres:14
    environment:
      POSTGRES_USER: mbdev
      POSTGRES_PASSWORD: mbdev
      POSTGRES_DB: memorybook-test
    ports:
      - 5433:5432
